// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web =  FirebaseOptions(
    apiKey: 'AIzaSyB6ZFDkYYYwm17FqxPrg_FiH3mS5aoes8E',
    appId: '1:178701694338:web:a53bb66b018b7360308b9b',
    messagingSenderId: '178701694338',
    projectId: 'discountkeeper-2be8e',
    authDomain: 'discountkeeper-2be8e.firebaseapp.com',
    storageBucket: 'discountkeeper-2be8e.appspot.com',
    measurementId: 'G-LLH13MQ6Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvl2USuVV81BiEVisBHCpt0Z-53xyHafk',
    appId: '1:178701694338:android:0029c0ecacdeb4bb308b9b',
    messagingSenderId: '178701694338',
    projectId: 'discountkeeper-2be8e',
    storageBucket: 'discountkeeper-2be8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCKmkQnzbOHoxAJwVNqMxR1NMNmgYCOU',
    appId: '1:178701694338:ios:c8749c9fed64b06c308b9b',
    messagingSenderId: '178701694338',
    projectId: 'discountkeeper-2be8e',
    storageBucket: 'discountkeeper-2be8e.appspot.com',
    iosBundleId: 'com.example.discountkeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQCKmkQnzbOHoxAJwVNqMxR1NMNmgYCOU',
    appId: '1:178701694338:ios:c8749c9fed64b06c308b9b',
    messagingSenderId: '178701694338',
    projectId: 'discountkeeper-2be8e',
    storageBucket: 'discountkeeper-2be8e.appspot.com',
    iosBundleId: 'com.example.discountkeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6ZFDkYYYwm17FqxPrg_FiH3mS5aoes8E',
    appId: '1:178701694338:web:43450cfafc2cfa43308b9b',
    messagingSenderId: '178701694338',
    projectId: 'discountkeeper-2be8e',
    authDomain: 'discountkeeper-2be8e.firebaseapp.com',
    storageBucket: 'discountkeeper-2be8e.appspot.com',
    measurementId: 'G-MDFRE0EPMK',
  );
}
